// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3dSw17Q7G-ASEcuQ8REufwy_YQLqYfnM',
    appId: '1:930344622459:web:b04be97854639cb9f405de',
    messagingSenderId: '930344622459',
    projectId: 'medipoint-90241',
    authDomain: 'medipoint-90241.firebaseapp.com',
    storageBucket: 'medipoint-90241.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXTUjFrNnNK9Ek1yqble95fnLg0dfqdgA',
    appId: '1:930344622459:android:b4c4aec97b938a45f405de',
    messagingSenderId: '930344622459',
    projectId: 'medipoint-90241',
    storageBucket: 'medipoint-90241.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwtQR8WCpL6ndHvuLaae8QwjFyuxw-X_8',
    appId: '1:930344622459:ios:8a8302e86839fc5bf405de',
    messagingSenderId: '930344622459',
    projectId: 'medipoint-90241',
    storageBucket: 'medipoint-90241.appspot.com',
    iosBundleId: 'com.example.medipoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwtQR8WCpL6ndHvuLaae8QwjFyuxw-X_8',
    appId: '1:930344622459:ios:4f84be187a8c75f7f405de',
    messagingSenderId: '930344622459',
    projectId: 'medipoint-90241',
    storageBucket: 'medipoint-90241.appspot.com',
    iosBundleId: 'com.example.medipoint.RunnerTests',
  );
}
